### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by mml1** [slape/prj-rev-bwfs-dasmoto#6]
[Meets Expectations] Fantastic job! You did so well using relative links. Relative links can be a bit tricky and it is great you are practicing now. In addition, I liked that you made an attempt to have alt tags for your images. Alt tags help screen readers, machines/programs used by individuals with impaired vision, describe your site to your user, thus making your site more accessible. Be sure to write a brief description about the image.

In terms of improvement, I would highly encourage you to pay close attention to your indentations. Having properly formatted code will make it easier to read and debug. Furthermore, take advantage of IDs. 

Overall, awesome work. Happy coding!

**Comment by slape** [comment]
Hi, Thanks so much for your feedback. 
Can you be a bit more specific about my indentations? I'm not sure I understand what/where I did something that was wrong. 

Also, as far as ID's go, do you suggest giving everything an ID, or just the major divs, or just particular items, etc?

**Comment by slape** [comment]
Sry, I found the other feedback with more info. 
I have no further questions. Thank you!
